### ISSUE TITLE
feedback_required

### ISSUE THREAD

**Issue by rodrigae** [instagram4j/instagram4j#350]
InstagramRequest:132 - Reading StatusResult from {"message": "feedback_required", "spam": true, "feedback_title": "Action Blocked", "feedback_message": "This action was blocked.

Does anyone know how to respond to this, there is an URL that is waiting for a respond. I think we can send back, no this is not a spam. I can't seem to figure it out.

**Comment by alejandropablo** [comment]
No, nothing to do here. Change the IP.

**Comment by rodrigae** [comment]
Damn, I’ve tried that but still happens and I even lowered the liking to below minimum and still happens

**Comment by ChrisJSt** [comment]
Happens to me as well. Very frustrating. Also tried changing IP's, decreasing the number of actions and increasing time between actions, and still eventually get spam flagged too.

**Comment by glani** [comment]
Guys a short question. Do you use it for many requests (real bots or for yourself) ? How many requests per second ?

**Comment by rodrigae** [comment]
So my damn code was looping through a list and not pausing when it failed, so instagram was getting hit like a spam. leading to feedback_required. stupid me lol, lets see if it fixes the issue.

**Comment by rodrigae** [comment]
I pause between 100-60 seconds per request, others 150-90 secs per request, but that didn't matter when the failed happen, it was being skipped. I believe that was my problem, I am currently testing it.

**Comment by ChrisJSt** [comment]
I leave about 30-50 seconds per request, and within a span of 2 hours will follow 30 people and like 90 photos.

**Comment by ryumaev** [comment]
In my case it's not throttling. Any follow request in my account (I used before for a lot of  follow requests) returns `feedback_required` but I tried goinsta library and everything works fine. So I think something is wrong on sending request. I'm migrating to goinsta it's more pretty library:)

**Comment by rodrigae** [comment]
ChrisJST, the Follow I noticed in the past anything below 60 secs would cause the blocking, so I recommend you increase it. I believe every limit gets reset every hour, so thats why i keep my randoms above 90 seconds. Before this issue, my likes and follows would be around 230 - 250 a day, then sleep for 8 hours. Still working on this current issue, no updates yet. Ryumaev, whats this library? goinsta, got a link?

**Comment by ChrisJSt** [comment]
I don't believe this is based off of the action count. I have been limiting my actions to 15 follows an hour, and I still get spammed out, meanwhile another account that I run is able to run no problem without getting any spam feedback. This issue has known to be affecting a lot of IG bots recently, as I believe IG updated their spam algorithms. I am going to pause my activity for a week and see, nothing else I can think of atm, tried everything :/

**Comment by rodrigae** [comment]
damn, no luck on the delay. I wish @ryumaev  would tell us whats the new API he using since this is not working anymore.

**Comment by alejandropablo** [comment]
That other API is not in Java.

**Comment by rodrigae** [comment]
Is it the one that says language Go? @alejandropablo

**Comment by rodrigae** [comment]
Today I tried a premium proxy, that means no one was using it, with delays over 150 secs, and eventually got the spam. I’m gonna have to learn a new language.

**Comment by alejandropablo** [comment]
jaja

It is defintely a combination of IP, this wrapper, and the messages.

**Comment by ryumaev** [comment]
I just using https://github.com/ahmdrz/goinsta ,  golang lib

**Comment by jvogit** [comment]
Addressed in [rewrite](https://github.com/instagram4j/instagram4j/tree/develop) or no longer relevant.

**Comment by albertocerqueira** [comment]
> ChrisJST, the Follow I noticed in the past anything below 60 secs would cause the blocking, so I recommend you increase it. I believe every limit gets reset every hour, so thats why i keep my randoms above 90 seconds. Before this issue, my likes and follows would be around 230 - 250 a day, then sleep for 8 hours. Still working on this current issue, no updates yet. Ryumaev, whats this library? goinsta, got a link?

Any solution?

**Comment by albertocerqueira** [comment]
> damn, no luck on the delay. I wish @ryumaev would tell us whats the new API he using since this is not working anymore.

I'm working with 180sec per request and I still have the problem = [

**Comment by albertocerqueira** [comment]
> Today I tried a premium proxy, that means no one was using it, with delays over 150 secs, and eventually got the spam. I’m gonna have to learn a new language.

I'm working with 180sec per request and I still have the problem = [
