### ISSUE TITLE
Login: IGResponseException: Please wait a few minutes before you try again.

### ISSUE THREAD

**Issue by calves07** [instagram4j/instagram4j#590]
Hey,
I've been getting an error during login for over a hour now
`Login: IGResponseException: Please wait a few minutes before you try again.`
I understand the error is due to limits being reached as I was always performing a new login every time I executed the application. 
After I started getting the error, I implemented a logic to serialize a successful login and always try to deserialize the login when the application starts and only login if it's not possible to deserialize so this should prevent this from happening again, but do you have any ideia what's the limit? I would expect it wouldn't take more than 1 hour to refresh.

**Comment by rushmedev** [comment]
I am also getting same issue. In my local system it is working fine but when I deployed my application to azure with same credentials this issue pops up.

**Comment by calves07** [comment]
It may be due to IP address, I've heart that sometimes these limits are applied to IP addresses. However, I setup a VPN and my problem persists so who knows... anyway, my limit has refreshed, it took a little more than 24 hours, I believe, probably close to 26.
